### ISSUE TITLE
feature - ssl pinning 

### ISSUE THREAD

**Issue by johndpope** [crescentflare/AppConfigSwift#1]
Great job on this library.
Where I'm working - there's a need to do ssl pinning - did you come across this? 

You seem to have successfully adding specific variables per environment - I guess it would be straight forward to support this. 

```
func HeaderValueFromClientIdHeader(clientIdHeader: ClientIdHeaderValue) -> String {
    let headerValue = 'SSL PIN HERE '
    return headerValue
}

func PinningPolicyNone() -> AFSecurityPolicy {
    return AFSecurityPolicy(pinningMode: AFSSLPinningMode.None)
}

func PinningPolicyDefault() -> AFSecurityPolicy {
    let policy = AFSecurityPolicy(pinningMode: AFSSLPinningMode.Certificate)
    policy.validatesCertificateChain = false

   return policy
}
```

**Comment by crescentflare** [comment]
Yes, I've needed SSL pinning in several projects. In each of these situations, I've added one or more settings (a boolean or an enum) to the app config model (to enable/disable pinning or specify the certificate), and did the rest of the implementation inside the app specific code.

This way I keep the library itself clean and without any dependencies (so anyone using it, can choose either AFNetworking, Alamofire or another custom library)
