### ISSUE TITLE
enhancement - expose some buttons to toggle in app logging.

### ISSUE THREAD

**Issue by johndpope** [crescentflare/AppConfigSwift#3]
I'm using dotzu library for in app logging - and want to be able to toggle buttons in config to disable / enable things. 

I'm thinking the editable configuration is good - but for testers - they just want to be able to turn off. 
I was thinking of having expandable tableview - that would drop down for existing configurations. 
I'll take a look a codebase when I get time and perhaps submit a PR.

**Comment by crescentflare** [comment]
With release 1.0.0 you can actually define a log level global setting which is shown below the configuration selection (see the example)
