### ISSUE TITLE
seeing hanging on iphoneX - not sure why....

### ISSUE THREAD

**Issue by wwe-johndpope** [crescentflare/AppConfigSwift#4]
it just become unresponsive.
am using swift 4. 

FAILED isOpenCounter: 1
FAILED AppConfigStorage.shared.isActivated: (Function)

**Comment by crescentflare** [comment]
This library will be migrated to swift 4 soon, hopefully that will solve the issue

**Comment by crescentflare** [comment]
Swift 4 conversion is complete (version 0.7.3 is available). Running the library was tested successfully on the iPhone X simulator.
